apiVersion: skaffold/v2alpha3
kind: Config
deploy:
  kubectl:
    manifests:
      - ./infra/k8s/*
build:
  # local:
  #   push: false

  googleCloudBuild:
    projectId: <add gke project reference here>
  artifacts:
    - image: <add gke project reference here>/account
      context: account
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: '/**/*.js'
            dest: .

        