apiVersion: apps/v1
kind: Deployment
metadata:
  name: inventory-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: inventory
  template:
    metadata:
      labels:
        app: inventory
    spec:
      containers:
        - name: inventory
          image: <add gke project reference here>/inventory
          env:
            - name: MONGO_URI
              value: 'mongodb://mongo-0.mongo,mongo-1.mongo,mongo-2.mongo:27017/inventory'
            - name: JWT_KEY
              valueFrom:
                  secretKeyRef:
                    name: jwt-secret
                    key: JWT_KEY 
---
apiVersion: v1
kind: Service
metadata:
  name: inventory-srv
spec:
  selector:
    app: inventory
  ports:
    - name: inventory
      protocol: TCP
      port: 3000
      targetPort: 3000
